name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Execute shell script
        run: |
          wget -q -O bibop https://apps.kaos.st/bibop/7.2.1/linux/x86_64/bibop
          chmod +x bibop
          ./bibop --help
