name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Print env info
        run: printenv | sort -h
      
      - name: Execute shell script
        run: |
          stat /proc/self/fd/0
          stat /proc/self/fd/1
          stat /proc/self/fd/2
          wget -q -O bibop https://apps.kaos.st/bibop/7.2.1/linux/x86_64/bibop?r=$INVOCATION_ID
          chmod +x bibop
          ./bibop -v
          ./bibop -v | head -100
