name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Restore permissions
        run: |
          wget https://apps.kaos.st/bibop/latest/linux/x86_64/bibop
          chmod +x bibop
          bibop --help
